package com.bitwave.cowdash.objects;

public enum ObjectType {

    OBJECT_BIRDY, OBJECT_BOUNCING_WALL, OBJECT_CHEST, OBJECT_DOOR, OBJECT_GOLDEN_VEGGIE,
    OBJECT_KEY, PLAYER, OBJECT_RUBY, OBJECT_TELEPORT, OBJECT_VEGGIE,
    ENEMY_BLOCK, ENEMY_JUMPING, ENEMY_SPIKE, ENEMY_TRAMP_HOG, ENEMY_WALKING, SCENERY

}
